# Generated by Django 2.1.7 on 2019-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfgLookup',
            fields=[
                ('choice', models.CharField(blank=True, db_column='Choice', max_length=25, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='TypeId', null=True)),
                ('uniquekey', models.CharField(db_column='UniqueKey', max_length=22, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cfg_Lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Cfg_Type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primarykey', models.CharField(db_column='PrimaryKey', max_length=22)),
                ('picture', models.ImageField(db_column='PictureURL', upload_to='')),
                ('embedding', models.TextField(db_column='Embedding')),
            ],
            options={
                'db_table': 'Image_Data',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('date_created', models.DateTimeField(blank=True, db_column='Date Created', null=True)),
                ('date_modified', models.DateTimeField(blank=True, db_column='Date Modified', null=True)),
                ('first_name', models.CharField(blank=True, db_column='First Name', max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='Middle Name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last Name', max_length=20, null=True)),
                ('name_to_call_me', models.CharField(blank=True, db_column='Name to Call Me', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('home_address', models.CharField(blank=True, db_column='Home Address', max_length=40, null=True)),
                ('home_city', models.CharField(blank=True, db_column='Home City', max_length=25, null=True)),
                ('home_state', models.CharField(blank=True, db_column='Home State', max_length=2, null=True)),
                ('home_zip', models.CharField(blank=True, db_column='Home Zip', max_length=10, null=True)),
                ('home_phone', models.CharField(blank=True, db_column='Home Phone', max_length=13, null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('dob_year', models.IntegerField(blank=True, db_column='DOB_YEAR', null=True)),
                ('hair', models.CharField(blank=True, db_column='Hair', max_length=10, null=True)),
                ('eyes', models.CharField(blank=True, db_column='Eyes', max_length=10, null=True)),
                ('race', models.CharField(blank=True, db_column='Race', max_length=1, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
                ('picture', models.BinaryField(blank=True, db_column='Picture', null=True)),
                ('picture_date', models.DateTimeField(blank=True, db_column='Picture Date', null=True)),
                ('emergency_contact_1_name', models.CharField(blank=True, db_column='Emergency Contact 1 Name', max_length=30, null=True)),
                ('emergency_contact_1_phone', models.CharField(blank=True, db_column='Emergency Contact 1 Phone', max_length=20, null=True)),
                ('emergency_contact_1_relationship', models.CharField(blank=True, db_column='Emergency Contact 1 Relationship', max_length=20, null=True)),
                ('emergency_contact_1_address', models.CharField(blank=True, db_column='Emergency Contact 1 Address', max_length=50, null=True)),
                ('emergency_contact_1_comments', models.TextField(blank=True, db_column='Emergency Contact 1 Comments', null=True)),
                ('emergency_contact_2_name', models.CharField(blank=True, db_column='Emergency Contact 2 Name', max_length=30, null=True)),
                ('emergency_contact_2_phone', models.CharField(blank=True, db_column='Emergency Contact 2 Phone', max_length=20, null=True)),
                ('emergency_contact_2_relationship', models.CharField(blank=True, db_column='Emergency Contact 2 Relationship', max_length=20, null=True)),
                ('emergency_contact_2_address', models.CharField(blank=True, db_column='Emergency Contact 2 Address', max_length=50, null=True)),
                ('emergency_contact_2_comments', models.TextField(blank=True, db_column='Emergency Contact 2 Comments', null=True)),
                ('emergency_contact_3_name', models.CharField(blank=True, db_column='Emergency Contact 3 Name', max_length=30, null=True)),
                ('emergency_contact_3_phone', models.CharField(blank=True, db_column='Emergency Contact 3 Phone', max_length=20, null=True)),
                ('emergency_contact_3_relationship', models.CharField(blank=True, db_column='Emergency Contact 3 Relationship', max_length=20, null=True)),
                ('emergency_contact_3_address', models.CharField(blank=True, db_column='Emergency Contact 3 Address', max_length=50, null=True)),
                ('emergency_contact_3_comments', models.TextField(blank=True, db_column='Emergency Contact 3 Comments', null=True)),
                ('emergency_contact_4_name', models.CharField(blank=True, db_column='Emergency Contact 4 Name', max_length=30, null=True)),
                ('emergency_contact_4_phone', models.CharField(blank=True, db_column='Emergency Contact 4 Phone', max_length=20, null=True)),
                ('emergency_contact_4_relationship', models.CharField(blank=True, db_column='Emergency Contact 4 Relationship', max_length=20, null=True)),
                ('emergency_contact_4_address', models.CharField(blank=True, db_column='Emergency Contact 4 Address', max_length=50, null=True)),
                ('emergency_contact_4_comments', models.TextField(blank=True, db_column='Emergency Contact 4 Comments', null=True)),
                ('emergency_contact_5_name', models.CharField(blank=True, db_column='Emergency Contact 5 Name', max_length=30, null=True)),
                ('emergency_contact_5_phone', models.CharField(blank=True, db_column='Emergency Contact 5 Phone', max_length=20, null=True)),
                ('emergency_contact_5_relationship', models.CharField(blank=True, db_column='Emergency Contact 5 Relationship', max_length=20, null=True)),
                ('emergency_contact_5_address', models.CharField(blank=True, db_column='Emergency Contact 5 Address', max_length=50, null=True)),
                ('emergency_contact_5_comments', models.TextField(blank=True, db_column='Emergency Contact 5 Comments', null=True)),
                ('organization', models.CharField(blank=True, db_column='Organization', max_length=30, null=True)),
                ('record_type', models.CharField(blank=True, db_column='Record Type', max_length=30, null=True)),
                ('braclet_id', models.CharField(blank=True, db_column='Braclet ID', max_length=20, null=True)),
                ('emergency_contact_1_cphone', models.CharField(blank=True, db_column='Emergency Contact 1 CPhone', max_length=20, null=True)),
                ('emergency_contact_2_cphone', models.CharField(blank=True, db_column='Emergency Contact 2 CPhone', max_length=20, null=True)),
                ('emergency_contact_3_cphone', models.CharField(blank=True, db_column='Emergency Contact 3 CPhone', max_length=20, null=True)),
                ('emergency_contact_4_cphone', models.CharField(blank=True, db_column='Emergency Contact 4 CPhone', max_length=20, null=True)),
                ('emergency_contact_5_cphone', models.CharField(blank=True, db_column='Emergency Contact 5 CPhone', max_length=20, null=True)),
                ('primarykey', models.CharField(db_column='PrimaryKey', max_length=22, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TAKEMEHOME',
            },
        ),
    ]
