# Generated by Django 2.1.7 on 2019-05-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='person',
            field=models.OneToOneField(max_length=22, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tmh.Person'),
        ),
    ]
