# Generated by Django 2.1.7 on 2019-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='embedding',
            field=models.TextField(blank=True, db_column='Embedding', null=True),
        ),
    ]
